name: CI

on:
  push:
    branches:
      - master
      - '0.6'
      - '0.8.x'
      - v*
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10, 12, 14]
        exclude:
          - os: macos-latest
            node: 10
          - os: macos-latest
            node: 12
          - os: windows-latest
            node: 10
          - os: windows-latest
            node: 12
      fail-fast: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - uses: nick-invision/retry@v3.0.0
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_on: error
          command: npm test
      - run: sudo apt-get install -y libgtk2.0-0
        if: runner.os == 'Linux'
      - name: npm run integration
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm run integration

  browser-tests:
    name: browser-tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: 'sauce'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - run: npm ci
      - run: npm run browser-tests
        env:
          SAUCE_USERNAME: testem-ci
          SAUCE_ACCESS_KEY: 1f00979e-0252-4d69-98ff-f6c85d1a746b
